### ISSUE TITLE
Operating environment issues

### ISSUE THREAD

**Issue by zihaoyy** [woozzzy/nft-generator#1]
Can you provide the respective operating environments and operating commands of the three directories? Thank you so much!

**Comment by woozzzy** [comment]
Hey! I just updated the readme to include a link to a notion page that contains pretty much everything. Let me know if you need anything else.

**Comment by zihaoyy** [comment]
> 



> Hey! I just updated the readme to include a link to a notion page that contains pretty much everything. Let me know if you need anything else.

Excellent! I will try to use this to do some nft
